version: "3.9"
services:
  mistral:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mistral_container
    volumes:
      - .:/inteligentEnvironment-
    working_dir: /inteligentEnvironment-
    command: python3 main.py
