

services:
  mistral:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intelligent_environment_mistral_container
    volumes:
      - .:/inteligentEnvironment
    working_dir: /inteligentEnvironment
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
