name : intelligentEnvironment
dependencies:
  - python=3.10
  - tensorflow
  - streamlit
  - pandas
  - safetensors
  - pip
  - pip:
      - transformers
      - torch
      - bitsandbytes
      - accelerate
      - streamlit
      - plotly
      - yaml
      - auto-gptq
      - optimum

